# Generated by Django 4.0.3 on 2022-03-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdNumber', models.CharField(max_length=120)),
                ('TCNumber', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=120)),
                ('surname', models.CharField(max_length=120)),
                ('tel', models.CharField(max_length=11)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
            ],
        ),
    ]
