# Generated by Django 4.0.3 on 2022-03-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='IdNumber',
        ),
        migrations.AlterField(
            model_name='form',
            name='TCNumber',
            field=models.CharField(max_length=11, verbose_name='TC kimlik numarası'),
        ),
        migrations.AlterField(
            model_name='form',
            name='city',
            field=models.CharField(max_length=120, verbose_name='Şehir'),
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(max_length=120, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='form',
            name='state',
            field=models.CharField(max_length=120, verbose_name='İlçe'),
        ),
        migrations.AlterField(
            model_name='form',
            name='surname',
            field=models.CharField(max_length=120, verbose_name='Soyisim'),
        ),
        migrations.AlterField(
            model_name='form',
            name='tel',
            field=models.CharField(max_length=11, verbose_name='Telefon'),
        ),
    ]
