# Generated by Django 4.0.3 on 2022-03-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_remove_form_idnumber_alter_form_tcnumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='id',
        ),
        migrations.AddField(
            model_name='form',
            name='Id',
            field=models.AutoField(default=123, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
