# Generated by Django 4.0.3 on 2022-03-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_remove_form_id_form_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='Id',
        ),
        migrations.AddField(
            model_name='form',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
