# Generated by Django 4.0.3 on 2022-03-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_remove_form_id_form_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='id',
        ),
        migrations.AddField(
            model_name='form',
            name='Id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
