# Generated by Django 4.0.3 on 2022-03-04 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_remove_form_tcnumber_remove_form_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='TCNumber',
            field=models.CharField(default=0, max_length=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='TC kimlik numarası'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='tel',
            field=models.CharField(default=0, max_length=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='Telefon'),
            preserve_default=False,
        ),
    ]
